model_name: GCNII
data_name: arxiv
num_layers: 4
num_parts: 40
batch_size: 20
hidden_size: 256
pool_size: 2
lr: 0.01
weight_decay: 0.0
dropout: 0.
alpha: 0.2
lambda_l: 0.5
gcn_norm: True
grad_norm: False
gen_train_data_in_advance: True
feat_gpu: True
epochs: 500
