model_name: APPNP
data_name: citeseer
num_layers: 10
num_parts: 24
batch_size: 6
hidden_size: 64
lr: 0.01
weight_decay: 0.0005
dropout: 0.0
alpha: 0.1
gcn_norm: True
grad_norm: True
gen_train_data_in_advance: True
feat_gpu: True
epochs: 600
